<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Container\Repository\Branch.php';

/**
 * Test class for VersionControl_Hg_Container_Repository_Branch.
 * Generated by PHPUnit on 2011-05-18 at 16:42:09.
 */
class VersionControl_Hg_Container_Repository_BranchTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Container_Repository_Branch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Container_Repository_Branch;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
