<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Container\Repository\Revision.php';

/**
 * Test class for VersionControl_Hg_Container_Repository_Revision.
 * Generated by PHPUnit on 2011-05-18 at 16:42:47.
 */
class VersionControl_Hg_Container_Repository_RevisionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Container_Repository_Revision
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Container_Repository_Revision;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
