<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Command\Cat.php';

/**
 * Test class for VersionControl_Hg_Command_Cat.
 * Generated by PHPUnit on 2011-06-21 at 10:17:44.
 */
class VersionControl_Hg_Command_CatTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Command_Cat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Command_Cat;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRevision().
     */
    public function testRevision()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testTo().
     */
    public function testTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
