<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Command\Init.php';

/* unit test only tests the constructor and *directory* functions.
 * Functional tests will test execute() */

/**
 * Test class for VersionControl_Hg_Command_Init.
 * Generated by PHPUnit on 2011-05-18 at 12:22:52.
 */
class VersionControl_Hg_Command_InitTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Command_Init
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Command_Init;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDirectory_exists().
     */
    public function testDirectory_exists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDirectory_is_empty().
     */
    public function testDirectory_is_empty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
