<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Command\Revert.php';

/**
 * Test class for VersionControl_Hg_Command_Revert.
 * Generated by PHPUnit on 2011-05-18 at 16:33:40.
 */
class VersionControl_Hg_Command_RevertTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Command_Revert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Command_Revert;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
