<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\Container\Bundle.php';

/**
 * Test class for VersionControl_Hg_Container_Bundle.
 * Generated by PHPUnit on 2011-05-18 at 16:36:58.
 */
class VersionControl_Hg_Container_BundleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_Container_Bundle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_Container_Bundle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAddRevision().
     */
    public function testAddRevision()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRemoveRevision().
     */
    public function testRemoveRevision()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetPath().
     */
    public function testSetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
