<?php

require_once 'H:\Development\_Webroot\Trunk\VersionControl\Hg\CommandProxy.php';

/**
 * Test class for VersionControl_Hg_CommandProxy.
 * Generated by PHPUnit on 2011-05-03 at 21:51:26.
 */
class VersionControl_Hg_CommandProxyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var VersionControl_Hg_CommandProxy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new VersionControl_Hg_CommandProxy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSetCommand().
     */
    public function testSetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCommand().
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
